// flow-typed signature: a786008c6d883ba75a2ce882db79ac0f
// flow-typed version: <<STUB>>/async.parallel_v^0.5.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async.parallel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async.parallel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'async.parallel/index' {
  declare module.exports: $Exports<'async.parallel'>;
}
declare module 'async.parallel/index.js' {
  declare module.exports: $Exports<'async.parallel'>;
}
