// flow-typed signature: 86fbe4353436c14a10e9abcd331aceaf
// flow-typed version: <<STUB>>/html-tags_v^2.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-tags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-tags' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-tags/void' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-tags/index' {
  declare module.exports: $Exports<'html-tags'>;
}
declare module 'html-tags/index.js' {
  declare module.exports: $Exports<'html-tags'>;
}
declare module 'html-tags/void.js' {
  declare module.exports: $Exports<'html-tags/void'>;
}
