// flow-typed signature: f7c49d543e9ffe9549d319b0b2365527
// flow-typed version: <<STUB>>/is-electron_v^2.1.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-electron/index' {
  declare module.exports: $Exports<'is-electron'>;
}
declare module 'is-electron/index.js' {
  declare module.exports: $Exports<'is-electron'>;
}
