// flow-typed signature: 60f255c6f42c09538d2fd831fbbcc31b
// flow-typed version: <<STUB>>/lodash.isfunction_v^3.0.8/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isfunction'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isfunction' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isfunction/index' {
  declare module.exports: $Exports<'lodash.isfunction'>;
}
declare module 'lodash.isfunction/index.js' {
  declare module.exports: $Exports<'lodash.isfunction'>;
}
