// flow-typed signature: 72bc8bd0d019c4331a74ff0773b4b4df
// flow-typed version: <<STUB>>/lodash.isnil_v^4.0.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.isnil'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.isnil' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.isnil/index' {
  declare module.exports: $Exports<'lodash.isnil'>;
}
declare module 'lodash.isnil/index.js' {
  declare module.exports: $Exports<'lodash.isnil'>;
}
