// flow-typed signature: e4e7ac61553feff14cbe2cfd0b6da3ea
// flow-typed version: <<STUB>>/lodash.compose_v^2.4.1/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.compose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.compose/index' {
  declare module.exports: $Exports<'lodash.compose'>;
}
declare module 'lodash.compose/index.js' {
  declare module.exports: $Exports<'lodash.compose'>;
}
