language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - .jest
node_js:
  - 12
script:
  - yarn run test
  - yarn run build
  # - yarn run size
after_success:
  - test $TRAVIS_BRANCH = "master" && yarn run doc
  - test $TRAVIS_BRANCH = "master" && npx semantic-release
