language: node_js
cache:
  # yarn: true
  directories:
    - node_modules
# notifications:
#   email: false
node_js:
  - lts/*
script:
  -  npm run test && npm run report-coverage && npm run build
before_install:
# package-lock.json was introduced in npm@5
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
after_success:
  # - npm run report-coverage
#   - test $TRAVIS_BRANCH = "master" && npm run deploy-docs
#   - npx semantic-release