language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - yarn && lerna bootstrap --concurrency=1
  - npm install -g codecov
cache:
  directories:
  - $HOME/.yarn-cache
jobs:
  include:
    - stage: Unit Tests
      script: lerna test && lerna install -g codecov && lerna run coverage
    - stage: ES Lint & Flow
      script: lerna run lint && lerna run flow