// flow-typed signature: 853c1fc23bb2587c047e52f27d1ffd25
// flow-typed version: <<STUB>>/@blueeast/bluerain-os_v^0.1.0/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueeast/bluerain-os'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueeast/bluerain-os' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueeast/bluerain-os/dist/boot' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/layouts/404Page' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/layouts/IndexPage' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/layouts/Page' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/models/App' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/models/Plugin' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/postinit' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/provider' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/reducers' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/store' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registerComponents' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/AppRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/CallbackRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/ComponentRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/ConfigRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/PluginRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/router/index.android' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/router/index.ios' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/router/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/routes' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/utils/JsonSchemaToReact' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/async.parallel_v0.5.2' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/lodash.get_v4.4.2' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/lodash.kebabcase_v4.1.1' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/lodash.merge_v4.6.0' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/lodash.reject_v4.6.0' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/lodash.set_v4.3.2' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/react-redux_v5.0.6' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/react-router-dom_v4.1.2' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/reactxp_v0.42.0' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/redux_v3.7.2' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/boot' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/layouts/404Page' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/layouts/IndexPage' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/layouts/Page' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/models/App' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/models/Plugin' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/postinit' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/provider' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/reducers' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/store' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registerComponents' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/AppRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/CallbackRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/ComponentRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/ConfigRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/PluginRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/router/index.android' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/router/index.ios' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/router/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/routes' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/utils/JsonSchemaToReact' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/About' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Contact' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Header' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Home' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/pageStyles' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/ActionTypes' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/TodoFilters' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/containers/App' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/plugins/ApolloPlugin/defaultParams' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/plugins/ApolloPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/plugins/InternationalizationPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/plugins/ReduxDevtoolsPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/apps' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/plugin' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/webpack.config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/apps' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/plugins' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/client/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/webpack.config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/App.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/AppRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/Callbacks.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/ComponentRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/ConfigRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/JsonSchemaToReact.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueeast/bluerain-os/dist/boot.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/boot'>;
}
declare module '@blueeast/bluerain-os/dist/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/config'>;
}
declare module '@blueeast/bluerain-os/dist/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/index'>;
}
declare module '@blueeast/bluerain-os/dist/layouts/404Page.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/layouts/404Page'>;
}
declare module '@blueeast/bluerain-os/dist/layouts/IndexPage.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/layouts/IndexPage'>;
}
declare module '@blueeast/bluerain-os/dist/layouts/Page.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/layouts/Page'>;
}
declare module '@blueeast/bluerain-os/dist/models/App.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/models/App'>;
}
declare module '@blueeast/bluerain-os/dist/models/Plugin.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/models/Plugin'>;
}
declare module '@blueeast/bluerain-os/dist/postinit.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/postinit'>;
}
declare module '@blueeast/bluerain-os/dist/redux/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/index'>;
}
declare module '@blueeast/bluerain-os/dist/redux/provider.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/provider'>;
}
declare module '@blueeast/bluerain-os/dist/redux/reducers.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/reducers'>;
}
declare module '@blueeast/bluerain-os/dist/redux/store.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/store'>;
}
declare module '@blueeast/bluerain-os/dist/registerComponents.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registerComponents'>;
}
declare module '@blueeast/bluerain-os/dist/registries/AppRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/AppRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/CallbackRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/CallbackRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/ComponentRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/ComponentRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/ConfigRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/ConfigRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/PluginRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/PluginRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/router/index.android.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/router/index.android'>;
}
declare module '@blueeast/bluerain-os/dist/router/index.ios.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/router/index.ios'>;
}
declare module '@blueeast/bluerain-os/dist/router/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/router/index'>;
}
declare module '@blueeast/bluerain-os/dist/routes.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/routes'>;
}
declare module '@blueeast/bluerain-os/dist/utils/JsonSchemaToReact.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/utils/JsonSchemaToReact'>;
}
declare module '@blueeast/bluerain-os/flow-typed/async.parallel_v0.5.2.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/async.parallel_v0.5.2'>;
}
declare module '@blueeast/bluerain-os/flow-typed/lodash.get_v4.4.2.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/lodash.get_v4.4.2'>;
}
declare module '@blueeast/bluerain-os/flow-typed/lodash.kebabcase_v4.1.1.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/lodash.kebabcase_v4.1.1'>;
}
declare module '@blueeast/bluerain-os/flow-typed/lodash.merge_v4.6.0.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/lodash.merge_v4.6.0'>;
}
declare module '@blueeast/bluerain-os/flow-typed/lodash.reject_v4.6.0.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/lodash.reject_v4.6.0'>;
}
declare module '@blueeast/bluerain-os/flow-typed/lodash.set_v4.3.2.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/lodash.set_v4.3.2'>;
}
declare module '@blueeast/bluerain-os/flow-typed/react-redux_v5.0.6.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/react-redux_v5.0.6'>;
}
declare module '@blueeast/bluerain-os/flow-typed/react-router-dom_v4.1.2.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/react-router-dom_v4.1.2'>;
}
declare module '@blueeast/bluerain-os/flow-typed/reactxp_v0.42.0.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/reactxp_v0.42.0'>;
}
declare module '@blueeast/bluerain-os/flow-typed/redux_v3.7.2.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/redux_v3.7.2'>;
}
declare module '@blueeast/bluerain-os/index' {
  declare module.exports: $Exports<'@blueeast/bluerain-os'>;
}
declare module '@blueeast/bluerain-os/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os'>;
}
declare module '@blueeast/bluerain-os/src/boot.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/boot'>;
}
declare module '@blueeast/bluerain-os/src/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/config'>;
}
declare module '@blueeast/bluerain-os/src/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/index'>;
}
declare module '@blueeast/bluerain-os/src/layouts/404Page.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/layouts/404Page'>;
}
declare module '@blueeast/bluerain-os/src/layouts/IndexPage.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/layouts/IndexPage'>;
}
declare module '@blueeast/bluerain-os/src/layouts/Page.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/layouts/Page'>;
}
declare module '@blueeast/bluerain-os/src/models/App.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/models/App'>;
}
declare module '@blueeast/bluerain-os/src/models/Plugin.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/models/Plugin'>;
}
declare module '@blueeast/bluerain-os/src/postinit.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/postinit'>;
}
declare module '@blueeast/bluerain-os/src/redux/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/index'>;
}
declare module '@blueeast/bluerain-os/src/redux/provider.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/provider'>;
}
declare module '@blueeast/bluerain-os/src/redux/reducers.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/reducers'>;
}
declare module '@blueeast/bluerain-os/src/redux/store.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/store'>;
}
declare module '@blueeast/bluerain-os/src/registerComponents.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registerComponents'>;
}
declare module '@blueeast/bluerain-os/src/registries/AppRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/AppRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/CallbackRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/CallbackRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/ComponentRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/ComponentRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/ConfigRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/ConfigRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/PluginRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/PluginRegistry'>;
}
declare module '@blueeast/bluerain-os/src/router/index.android.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/router/index.android'>;
}
declare module '@blueeast/bluerain-os/src/router/index.ios.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/router/index.ios'>;
}
declare module '@blueeast/bluerain-os/src/router/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/router/index'>;
}
declare module '@blueeast/bluerain-os/src/routes.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/routes'>;
}
declare module '@blueeast/bluerain-os/src/utils/JsonSchemaToReact.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/utils/JsonSchemaToReact'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/About.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/About'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Contact.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Contact'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Header.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Header'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Home.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Home'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/pageStyles.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/pageStyles'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/ActionTypes.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/ActionTypes'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/TodoFilters.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/TodoFilters'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/containers/App.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/containers/App'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/plugins/ApolloPlugin/defaultParams.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/plugins/ApolloPlugin/defaultParams'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/plugins/ApolloPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/plugins/ApolloPlugin/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/plugins/InternationalizationPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/plugins/InternationalizationPlugin/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/plugins/ReduxDevtoolsPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/plugins/ReduxDevtoolsPlugin/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/apps.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/apps'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/config'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/plugin.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/plugin'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/webpack.config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/webpack.config'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/apps.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/apps'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/config'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/plugins.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/plugins'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/client/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/client/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/webpack.config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/webpack.config'>;
}
declare module '@blueeast/bluerain-os/tests/unit/App.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/App.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/AppRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/AppRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/Callbacks.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/Callbacks.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/ComponentRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/ComponentRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/ConfigRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/ConfigRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/JsonSchemaToReact.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/JsonSchemaToReact.test'>;
}
