# Used on master, the only difference is that we release docs here

name: Production CI

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "master" # Push events on master branch

jobs:
  test:
    name: Test, Build & Release
    runs-on: ubuntu-latest
    container: 
      image: bluebasejs/github-actions-image

    strategy:
      matrix:
        node-version: [12]
        
    steps:
      - uses: actions/checkout@master

      - name: Install Dependencies
        run: yarn install

      - name: Unit Tests
        run: yarn test:only --coverage --logHeapUsage --ci

      - name: Test Lint
        run: yarn test:lint

      - name: Test Prettier
        run: yarn test:prettier

      - name: Build
        run: yarn build

      - name: Semantic Release
        env:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release@beta

      - name: Build Docs
        run: yarn run doc

      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v2.2.0
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
