// flow-typed signature: f49af6a47d101d6460c224d26ed5db12
// flow-typed version: <<STUB>>/@blueeast/bluerain-os_vgit://github.com/BlueEastCode/bluerain-os.git#next/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueeast/bluerain-os'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueeast/bluerain-os' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueeast/bluerain-os/dist/boot' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/layouts/ResponsiveLayout' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/layouts/SystemLayout' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/models/App' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/models/Plugin' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/pages/IndexPage' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/pages/NotFoundPage' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/pages/Page' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/Platform' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/ApolloPlugin/defaultParams' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/ApolloPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/defaultPlugins' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/InternationalizationPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/ReduxDevtoolsPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/actions' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/connect' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/getWindowSize' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/initialState' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/reducer' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/postinit' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/provider' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/reducers' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/redux/store' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registerComponents' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/AppRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/ComponentRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/ConfigRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/EventRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/FilterRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/registries/PluginRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/router/index.android' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/router/index.ios' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/router/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/routes' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/dist/utils/JsonSchemaToReact' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/async.parallel_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-plugin-react-transform_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-es2016_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-stage-2_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/babel-register_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/codacy-coverage_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/documentation_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-config-blueeast_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/eventemitter3_v2.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/history_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/is-electron_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/jest-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/json-loader_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.get_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.kebabcase_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.merge_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.reject_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.set_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/react-intl_v2.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/react-router-dom_v4.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/react-router-native_v4.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/reactxp_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/redux-mock-store_v1.2.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/subscriptions-transport-ws_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/todomvc-app-css_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/boot' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/layouts/ResponsiveLayout' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/layouts/SystemLayout' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/models/App' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/models/Plugin' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/pages/IndexPage' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/pages/NotFoundPage' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/pages/Page' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/Platform' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/ApolloPlugin/defaultParams' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/ApolloPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/defaultPlugins' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/InternationalizationPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/ReduxDevtoolsPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/actions' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/connect' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/getWindowSize' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/initialState' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/reducer' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/postinit' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/provider' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/reducers' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/redux/store' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registerComponents' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/AppRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/ComponentRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/ConfigRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/EventRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/FilterRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/registries/PluginRegistry' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/router/index.android' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/router/index.ios' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/router/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/routes' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/src/utils/JsonSchemaToReact' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/About' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Contact' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Header' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Home' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/pageStyles' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Responsive' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/ActionTypes' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/TodoFilters' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/containers/App' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.spec' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/apps' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/plugin' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/webpack.config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/apps' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/plugins' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/client/index' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/integration/web/todo/webpack.config' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/AppRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/boot.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/ComponentRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/ConfigRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/Event.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/FilterRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/JsonSchemaToReact.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/PluginRegistry.test' {
  declare module.exports: any;
}

declare module '@blueeast/bluerain-os/tests/unit/ResponsiveLayout.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueeast/bluerain-os/dist/boot.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/boot'>;
}
declare module '@blueeast/bluerain-os/dist/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/config'>;
}
declare module '@blueeast/bluerain-os/dist/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/index'>;
}
declare module '@blueeast/bluerain-os/dist/layouts/ResponsiveLayout.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/layouts/ResponsiveLayout'>;
}
declare module '@blueeast/bluerain-os/dist/layouts/SystemLayout.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/layouts/SystemLayout'>;
}
declare module '@blueeast/bluerain-os/dist/models/App.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/models/App'>;
}
declare module '@blueeast/bluerain-os/dist/models/Plugin.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/models/Plugin'>;
}
declare module '@blueeast/bluerain-os/dist/pages/IndexPage.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/pages/IndexPage'>;
}
declare module '@blueeast/bluerain-os/dist/pages/NotFoundPage.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/pages/NotFoundPage'>;
}
declare module '@blueeast/bluerain-os/dist/pages/Page.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/pages/Page'>;
}
declare module '@blueeast/bluerain-os/dist/Platform.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/Platform'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/ApolloPlugin/defaultParams.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/ApolloPlugin/defaultParams'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/ApolloPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/ApolloPlugin/index'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/defaultPlugins.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/defaultPlugins'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/InternationalizationPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/InternationalizationPlugin/index'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/ReduxDevtoolsPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/ReduxDevtoolsPlugin/index'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/actions.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/actions'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/connect.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/connect'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/getWindowSize.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/getWindowSize'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/index'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/initialState.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/initialState'>;
}
declare module '@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/reducer.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/plugins/WindowInfoPlugin/reducer'>;
}
declare module '@blueeast/bluerain-os/dist/postinit.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/postinit'>;
}
declare module '@blueeast/bluerain-os/dist/redux/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/index'>;
}
declare module '@blueeast/bluerain-os/dist/redux/provider.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/provider'>;
}
declare module '@blueeast/bluerain-os/dist/redux/reducers.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/reducers'>;
}
declare module '@blueeast/bluerain-os/dist/redux/store.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/redux/store'>;
}
declare module '@blueeast/bluerain-os/dist/registerComponents.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registerComponents'>;
}
declare module '@blueeast/bluerain-os/dist/registries/AppRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/AppRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/ComponentRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/ComponentRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/ConfigRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/ConfigRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/EventRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/EventRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/FilterRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/FilterRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/registries/PluginRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/registries/PluginRegistry'>;
}
declare module '@blueeast/bluerain-os/dist/router/index.android.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/router/index.android'>;
}
declare module '@blueeast/bluerain-os/dist/router/index.ios.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/router/index.ios'>;
}
declare module '@blueeast/bluerain-os/dist/router/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/router/index'>;
}
declare module '@blueeast/bluerain-os/dist/routes.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/routes'>;
}
declare module '@blueeast/bluerain-os/dist/utils/JsonSchemaToReact.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/dist/utils/JsonSchemaToReact'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/async.parallel_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/async.parallel_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-plugin-react-transform_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-plugin-react-transform_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-es2016_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-preset-es2016_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-preset-stage-2_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-preset-stage-2_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/babel-register_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/babel-register_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/classnames_v2.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/codacy-coverage_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/codacy-coverage_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/documentation_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/documentation_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-config-blueeast_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eslint-config-blueeast_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/eventemitter3_v2.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/eventemitter3_v2.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/history_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/history_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/is-electron_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/is-electron_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/jest_v20.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/jest-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/jest-cli_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/json-loader_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/json-loader_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.get_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/lodash.get_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.kebabcase_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/lodash.kebabcase_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.merge_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/lodash.merge_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.reject_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/lodash.reject_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/lodash.set_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/lodash.set_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/react-intl_v2.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/react-intl_v2.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/react-redux_v5.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/react-router-dom_v4.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/react-router-dom_v4.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/react-router-native_v4.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/react-router-native_v4.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/reactxp_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/reactxp_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/redux_v3.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/redux-mock-store_v1.2.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/redux-mock-store_v1.2.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/subscriptions-transport-ws_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/subscriptions-transport-ws_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/todomvc-app-css_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/todomvc-app-css_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/webpack_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/flow-typed/npm/webpack-dev-server_vx.x.x'>;
}
declare module '@blueeast/bluerain-os/index' {
  declare module.exports: $Exports<'@blueeast/bluerain-os'>;
}
declare module '@blueeast/bluerain-os/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os'>;
}
declare module '@blueeast/bluerain-os/src/boot.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/boot'>;
}
declare module '@blueeast/bluerain-os/src/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/config'>;
}
declare module '@blueeast/bluerain-os/src/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/index'>;
}
declare module '@blueeast/bluerain-os/src/layouts/ResponsiveLayout.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/layouts/ResponsiveLayout'>;
}
declare module '@blueeast/bluerain-os/src/layouts/SystemLayout.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/layouts/SystemLayout'>;
}
declare module '@blueeast/bluerain-os/src/models/App.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/models/App'>;
}
declare module '@blueeast/bluerain-os/src/models/Plugin.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/models/Plugin'>;
}
declare module '@blueeast/bluerain-os/src/pages/IndexPage.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/pages/IndexPage'>;
}
declare module '@blueeast/bluerain-os/src/pages/NotFoundPage.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/pages/NotFoundPage'>;
}
declare module '@blueeast/bluerain-os/src/pages/Page.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/pages/Page'>;
}
declare module '@blueeast/bluerain-os/src/Platform.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/Platform'>;
}
declare module '@blueeast/bluerain-os/src/plugins/ApolloPlugin/defaultParams.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/ApolloPlugin/defaultParams'>;
}
declare module '@blueeast/bluerain-os/src/plugins/ApolloPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/ApolloPlugin/index'>;
}
declare module '@blueeast/bluerain-os/src/plugins/defaultPlugins.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/defaultPlugins'>;
}
declare module '@blueeast/bluerain-os/src/plugins/InternationalizationPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/InternationalizationPlugin/index'>;
}
declare module '@blueeast/bluerain-os/src/plugins/ReduxDevtoolsPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/ReduxDevtoolsPlugin/index'>;
}
declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/actions.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/actions'>;
}
declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/connect.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/connect'>;
}
declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/getWindowSize.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/getWindowSize'>;
}
declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/index'>;
}
declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/initialState.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/initialState'>;
}
declare module '@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/reducer.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/plugins/WindowInfoPlugin/reducer'>;
}
declare module '@blueeast/bluerain-os/src/postinit.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/postinit'>;
}
declare module '@blueeast/bluerain-os/src/redux/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/index'>;
}
declare module '@blueeast/bluerain-os/src/redux/provider.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/provider'>;
}
declare module '@blueeast/bluerain-os/src/redux/reducers.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/reducers'>;
}
declare module '@blueeast/bluerain-os/src/redux/store.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/redux/store'>;
}
declare module '@blueeast/bluerain-os/src/registerComponents.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registerComponents'>;
}
declare module '@blueeast/bluerain-os/src/registries/AppRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/AppRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/ComponentRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/ComponentRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/ConfigRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/ConfigRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/EventRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/EventRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/FilterRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/FilterRegistry'>;
}
declare module '@blueeast/bluerain-os/src/registries/PluginRegistry.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/registries/PluginRegistry'>;
}
declare module '@blueeast/bluerain-os/src/router/index.android.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/router/index.android'>;
}
declare module '@blueeast/bluerain-os/src/router/index.ios.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/router/index.ios'>;
}
declare module '@blueeast/bluerain-os/src/router/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/router/index'>;
}
declare module '@blueeast/bluerain-os/src/routes.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/routes'>;
}
declare module '@blueeast/bluerain-os/src/utils/JsonSchemaToReact.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/src/utils/JsonSchemaToReact'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/About.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/About'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Contact.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Contact'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Header.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Header'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Home.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Home'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/pageStyles.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/pageStyles'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Responsive.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/components/Responsive'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/HelloWorldApp/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/actions/index.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Footer.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/Header.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/MainSection.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoItem.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/components/TodoTextInput.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/ActionTypes.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/ActionTypes'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/TodoFilters.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/constants/TodoFilters'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/containers/App.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/containers/App'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos'>;
}
declare module '@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.spec.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/common/apps/TodoMVCApp/reducers/todos.spec'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/apps.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/apps'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/config'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/plugin.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/src/app/plugin'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/hello-world/webpack.config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/hello-world/webpack.config'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/apps.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/apps'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/config'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/plugins.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/bluerain/plugins'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/src/client/index.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/src/client/index'>;
}
declare module '@blueeast/bluerain-os/tests/integration/web/todo/webpack.config.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/integration/web/todo/webpack.config'>;
}
declare module '@blueeast/bluerain-os/tests/unit/AppRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/AppRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/boot.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/boot.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/ComponentRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/ComponentRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/ConfigRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/ConfigRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/Event.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/Event.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/FilterRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/FilterRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/JsonSchemaToReact.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/JsonSchemaToReact.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/PluginRegistry.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/PluginRegistry.test'>;
}
declare module '@blueeast/bluerain-os/tests/unit/ResponsiveLayout.test.js' {
  declare module.exports: $Exports<'@blueeast/bluerain-os/tests/unit/ResponsiveLayout.test'>;
}
